version: '3'
services:
  some-api:
    container_name: some-api
    user: root
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  
  loki:
    container_name: loki
    image: grafana/loki:latest
    user: root
    restart: always
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml      
    depends_on:
      - some-api

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    user: root
    restart: always
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./deployments/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - some-api
      - loki

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    user: root
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./deployments/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    depends_on:
      - some-api

  grafana:
    container_name: grafana
    user: root
    build:
      context: ./deployments/grafana/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - some-api
      - loki
      - promtail    