version: '3'
services:
  some-dbms:
    container_name: some-dbms
    user: root
    restart: always
    image: postgres:10.6
    environment:
      - POSTGRES_ROLE=postgres
      - POSTGRES_USER=some_db_user
      - POSTGRES_PASSWORD=some_db_password
      - POSTGRES_DB=some_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 20s
      retries: 4

  some-api:
    container_name: some-api
    user: root
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - some-dbms
  
  loki:
    container_name: loki
    image: grafana/loki:2.1.0
    user: root
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./local/promtail:/promtail
    command: -config.file=/etc/loki/local-config.yaml      
    depends_on:
      - some-api

  promtail:
    container_name: promtail
    image: grafana/promtail:2.1.0
    user: root
    restart: always
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - ./deployments/promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - some-api
      - loki

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.23.0
    user: root
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./deployments/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./local/prometheus:/prometheus
    depends_on:
      - some-api

  grafana:
    container_name: grafana
    user: root
    build:
      context: ./deployments/grafana/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./local/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - some-api
      - loki
      - promtail    