version: '3'

services:
  loki:
    container_name: loki
    user: root
    restart: always
    build:
      context: loki/
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - ./local/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml      

  promtail:
    container_name: promtail
    user: root
    restart: always
    build:
      context: promtail/
      dockerfile: Dockerfile
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  prometheus:
    container_name: prometheus
    user: root
    restart: always
    build:
      context: prometheus/
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    volumes:
      - ./local/prometheus:/prometheus

  jaeger:
    container_name: jaeger
    user: root
    restart: always
    image: jaegertracing/all-in-one:latest
    ports:
    - 6831:6831
    - 16686:16686 
    volumes:
      - ./local/jaeger:/jaeger   

  grafana:
    container_name: grafana
    user: root
    restart: always
    build:
      context: grafana/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./local/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - promtail 

  some-dbms:
    container_name: some-dbms
    user: root
    restart: always
    image: postgres:10.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=some_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 20s
      retries: 4

  some-api-executing:
    container_name: some-api-executing
    user: root
    restart: always
    build:
      context: some-api-executing/
      dockerfile: Dockerfile
    depends_on:
      - some-api
  
  some-api:
    container_name: some-api
    user: root
    restart: always
    build:
      context: some-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - some-dbms