version: '3'
services:
  some-dbms:
    container_name: some-dbms
    user: root
    restart: always
    image: postgres:10.6
    environment:
      - POSTGRES_USER=some_db_user
      - POSTGRES_PASSWORD=some_db_password
      - POSTGRES_DB=some_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 20s
      retries: 4

  loki:
    container_name: loki
    user: root
    restart: always
    build:
      context: loki/
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - ./local/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    container_name: promtail
    user: root
    restart: always
    build:
      context: promtail/
      dockerfile: Dockerfile
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  prometheus:
    container_name: prometheus
    user: root
    restart: always
    build:
      context: prometheus/
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    volumes:
      - ./local/prometheus:/prometheus

  grafana:
    container_name: grafana
    user: root
    restart: always
    build:
      context: grafana/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./local/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - promtail