opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831

logging:
  appender:
    loki-sender:
      host: localhost

client:
  some-api: http://localhost:8081/some-data/instances/