server:
  port: 8182

opentracing:
  jaeger:
    udp-sender:
      host: localhost

logging:
  appender:
    loki-sender:
      host: localhost

amqp:
  rabbit:
    binder:
      brokers: localhost

client:
  some-api: http://localhost:8181/some-data/instances/