management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always

server:
  port: 8081

logging:
  file:
    max-size: 100MB
    path: .

  pattern:
    console: "%clr(%date{HH:mm:ss.SSS}) %level %clr(%logger{0}) : %message%n"
    file:    "%clr(%date) %level %clr(%logger :) %message%n"

  level:
    root: INFO
    org.springframework: INFO

spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    platform: postgres
    url: jdbc:postgresql://127.0.0.1/some_db
    username: some_db_user
    password: some_db_password

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      show-sql: true

    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  liquibase:
    change-log: classpath:db-migrations/changelog.xml
    enabled: true
    drop-first: false