apiVersion: 1

datasources:
  - name: Loki
    label: Loki
    uid: loki
    type: loki
    access: proxy
    url: loki:3100
    isDefault: true
    jsonData:
      derivedFields:
      datasourceUid: jaeger
      matcherRegex: traceId=(\w+)
      name: traceId
      url: $${__value.raw}
  
  - name: Jaeger
    label: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: jaeger:16686
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - service
          - host
          - level
          - logger
          - traceId     

  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    url: prometheus:9090
    isDefault: false
  
  - name: PostgreSQL
    label: PostgreSQL
    type: postgres
    access: proxy
    isDefault: false
    url: some-dbms:5432
    database: postgres
    user: some
    secureJsonData:
      password: "qwerty"
    basicAuth: false
    jsonData:
      sslmode: "disable"
      postgresVersion: 1000 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
    editable: true  