datasources:
  - name: Loki
    label: Loki
    uid: loki
    type: loki
    access: proxy
    url: loki:3100
    isDefault: true
    jsonData:
      maxLines: 10000
      derivedFields:
      datasourceUid: jaeger
      matcherRegex: traceId=(\w+)
      name: traceId
      url: $${__value.raw}
  
  - name: Jaeger
    label: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: jaeger:16686
    isDefault: false
    jsonData:
      tracesToLogs:
        datasourceUid: loki
        tags:
          - service
          - host
          - level
          - logger
          - traceId     

  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    url: prometheus:9090
    isDefault: false